Add neg function
v-jizhang/presto-test pull request #19
Opened 2023-01-09 18:59 UTC by jinlinzh

2023-01-10 22:47 UTC, v-jizhang requested changes
Change requested

2023-01-12 00:32 UTC, v-jizhang requested changes
Test change requested.

2023-01-23 23:38 UTC, jinlinzh commented
@prestobot kick off tests

2023-01-27 00:57 UTC, v-jizhang approved these changes
Approved

2023-02-16 16:36 UTC, closed without merging